#include "ExtendedDataTypes.idl" // openrtm

module contact_state_msgs
{

  struct ContactIdl
  {
    string link1; // URDF link name.
    RTC::Pose3D local_pose; // link1 local frame. Z軸がlink2からlink1へ向かう方向
    string link2; // URDF link name. ""ならworld.
    boolean free_x; // local_pose frame
    boolean free_y; // local_pose frame
  };

  struct TimedContactSeq
  {
    RTC::Time tm;
    sequence<ContactIdl> data;
  };
};
